services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/userdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network

  api:
    build: ./backend
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
